name: CREATE-MWODDACORE-SOLUTION-CONFIG

on:
  workflow_dispatch:
    inputs:
      ado_ticket_id:
        description: "ID of the task in ADO."
        required: true
        type: string
        default: "123"
      solution_name:
        description: "The name of the project (e.g., V2C, DSS)."
        required: true
        default: test
      solution_prefix:
        description: "A required prefix for the solution (default value: E2ESC)."
        default: ODDA
        required: true
      solution_product_short_name:
        description: "Solution Product Short Name"
        required: true
        default: "DCOMDEMANDDELIVERY"
      solution_resource_name:
        description: "Solution Resource Name"
        required: true
        default: "DCOMODD"
      
      module_version:
        description: "The version of the Snacking solution infrastructure template module to be used (e.g., 1.0.0). Always try to use the latest version."
        required: true
        type: string
        default: "3.0.3"
      enable_app_services:
        description: "Enable app services"
        required: true
        type: boolean
        default: true
      enable_storage_accounts:
        description: "Enable storage accounts"
        required: true
        type: boolean
        default: false
      enable_logic_app:
        description: "Enable logic_app"
        required: true
        type: boolean
        default: false
      enable_adf:
        description: "Enable azure data factory"
        required: true
        type: boolean
        default: false
      
      # enable_databricks:
      #   description: "Enable Databricks"
      #   required: true
      #   type: boolean
      #   default: true
      # enable_keyvault:
      #   description: "Enable KeyVault"
      #   required: true
      #   type: boolean
      #   default: true


permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create_new_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert to upper solution prefix and name 
        run: |
          echo "SOLUTION_NAME=$(echo "${{ inputs.solution_name }}" | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
          echo "SOLUTION_PREFIX=$(echo "${{ inputs.solution_prefix }}" | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
          echo "solution_product_short_name=$(echo "${{ inputs.solution_product_short_name }}" | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV

      - name: Create new branch
        run: |
          branch_name="feature/ID-${{ inputs.ado_ticket_id }}-DEV-${{ env.SOLUTION_PREFIX }}-${{ env.SOLUTION_NAME }}-CONFIG"
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
          git checkout -b $branch_name


      - name: Create config file
        run: |
          dest_config_dir_path="development/${{ env.SOLUTION_PREFIX }}-${{ env.solution_product_short_name }}-${{ env.SOLUTION_NAME }}-EUS2"
          echo "DEST_CONFIG_DIR_PATH=$dest_config_dir_path" >> $GITHUB_ENV
          mkdir -p $dest_config_dir_path
          ls -l

          # Copy non-parts files from tf_config to destination
          find templates/mwodda-snacking-solution-config-template/development/tf_config -maxdepth 1 -type f -exec cp {} $dest_config_dir_path/ \;
          config_file="$dest_config_dir_path/main.tf"
          touch $config_file
          ls -l $config_file

          # Copy module configuration (always required)
          cat templates/mwodda-snacking-solution-config-template/development/tf_config/parts/module.txt >> $config_file

          # Copy keyVault configuration
          cat templates/mwodda-snacking-solution-config-template/development/tf_config/parts/key_vault.txt >> $config_file

          # Copy databricks configuration
          cat templates/mwodda-snacking-solution-config-template/development/tf_config/parts/databricks.txt >> $config_file
          
          # Copy ADLS configuration
          cat templates/mwodda-snacking-solution-config-template/development/tf_config/parts/adls.txt >> $config_file

          # Conditionally include app_services block
          if ${{ inputs.enable_app_services }}; then
            cat templates/mwodda-snacking-solution-config-template/development/tf_config/parts/app_services.txt >> $config_file
          fi

          # Conditionally include storage_accounts block
          if ${{ inputs.enable_storage_accounts }}; then
            cat templates/mwodda-snacking-solution-config-template/development/tf_config/parts/storage_accounts.txt >> $config_file
          fi

          # Conditionally include logic_app block
          if ${{ inputs.enable_logic_app }} && ${{ inputs.enable_storage_accounts }}; then
            cat templates/mwodda-snacking-solution-config-template/development/tf_config/parts/logic_app.txt >> $config_file
          fi

          # Conditionally include adf with logic_app integration block
          if  ${{ inputs.enable_logic_app == 'true' && inputs.enable_adf == 'true' }}; then
            cat templates/mwodda-snacking-solution-config-template/development/tf_config/parts/adf_with_logicapp.txt >> $config_file
          fi

          # Conditionally include adf without logic_app integration block
          if  ${{ inputs.enable_logic_app == 'false' && inputs.enable_adf == 'true' }}; then
            cat templates/mwodda-snacking-solution-config-template/development/tf_config/parts/adf_without_logicapp.txt >> $config_file
          fi

          # Close the module block
          echo '}' >> $config_file
            

      - name: Replace placeholders in all files in the config directory
        run: |
          for file in "${{ env.DEST_CONFIG_DIR_PATH }}"/*; do
            sed -i "s/{solution_prefix}/${{ inputs.solution_prefix }}/g" "$file"
            sed -i "s/{solution_name}/${{ inputs.solution_name }}/g" "$file"
            sed -i "s/{solution_product_short_name}/${{ inputs.solution_product_short_name }}/g" "$file"
            sed -i "s/{solution_resource_name}/${{ inputs.solution_resource_name }}/g" "$file"
          done

      - name: Terraform fmt
        run: |
          cd ${{ env.DEST_CONFIG_DIR_PATH }}
          terraform fmt


      # - name: Rename workflow file 
      #   run: |
      #      wf_filename=$(echo "dev-${{ env.SOLUTION_PREFIX }}1-${{ env.solution_product_short_name }}${{ env.SOLUTION_NAME }}-eus2.yaml" | tr '[:upper:]' '[:lower:]')
      #      mv ${{ env.DEST_CONFIG_DIR_PATH }}/workflow.yaml ${{ env.DEST_CONFIG_DIR_PATH }}/$wf_filename
      #      mv ${{ env.DEST_CONFIG_DIR_PATH }}/$wf_filename .github/workflows/

      - name: Set git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Stage and commit changes
        run: |
          git add .
          git commit -m "Initial ${{ env.SOLUTION_PREFIX }}-${{ env.solution_product_short_name }}-${{ env.SOLUTION_NAME }}-EUS2 infrastructure configuration"

      - name: Push to remote
        run: git push --set-upstream origin ${{ env.BRANCH_NAME }}